src/main/java/com/gitlab/tplsofteng/gamecorral/backing/GamePageBean.java
package com.gitlab.tplsofteng.gamecorral.backing;

//~--- non-JDK imports --------------------------------------------------------

/*
* To change this template, choose Tools | Templates and open the template in
* the editor.
 */
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import java.io.ByteArrayInputStream;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import com.gitlab.tplsofteng.gamecorral.Entities.GamePackage;
import com.gitlab.tplsofteng.gamecorral.persistence.CrudServiceBean;

/**
 *
 * @author tplsofteng@gmail.com
 */
@ManagedBean
@RequestScoped
@URLMapping(
    id      = "gamePage",
    pattern = "/games/#{ gamePageBean.gameTitle }",
    viewId  = "/gamePage.xhtml"
)
public class GamePageBean extends GameSiteManagedBean {
    private GamePackage     currentGame;
    private CrudServiceBean dao;

    /**
     * Creates a new instance of gamesPageBean
     */
    
    private String gameTitle;

    public GamePageBean() 
    {
        dao = new CrudServiceBean();
    }

    public String getGame() 
    {
        long id = getDao().findGameIdByName(getGameTitle());

        currentGame = (GamePackage) getDao().find(GamePackage.class, id);

        if (currentGame != null)
        {
            return currentGame.getTitle();
        }
        
        else 
        {
            return "Unknown Game";
        }
    }

    public String getContent() 
    {
        String script;

        if (currentGame != null) 
        {
            if (currentGame.getGameFile() != null) 
            {
                script = new String(currentGame.getGameFile());
            }
            
            else 
            {
                script = "No Content error";
            }
            
        } 
        else 
        {
            script = "Game Not Found";
        }

        System.err.println("Script: " + script);

        return script;
    }

    public StreamedContent getThumb() 
    {
        ByteArrayInputStream   imgStream = new ByteArrayInputStream(currentGame.getThumb());
        DefaultStreamedContent thumb     = new DefaultStreamedContent(imgStream, "image/png");

        return thumb;
    }

    /**
     * @return the gameTitle
     */
    public String getGameTitle() {
        return gameTitle;
    }

    /**
     * @param gameTitle the gameTitle to set
     */
    public void setGameTitle(String gameTitle) {
        this.gameTitle = gameTitle;
    }

    /**
     * @return the currentGame
     */
    public GamePackage getCurrentGame() {
        return currentGame;
    }

    /**
     * @param currentGame the currentGame to set
     */
    public void setCurrentGame(GamePackage currentGame) {
        this.currentGame = currentGame;
    }

    /**
     * @return the dao
     */
    public CrudServiceBean getDao() {
        return dao;
    }

    public String getPageContent() 
    {
        if (currentGame != null) 
        {
            return this.currentGame.getPageData();
        } 
        else 
        {
            return "Game Not Found ";
        }
    }

    /**
     * @param dao the dao to set
     */
    public void setDao(CrudServiceBean dao) {
        this.dao = dao;
    }

    protected void reloadBackingData() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}


//~ Formatted by Jindent --- http://www.jindent.com

src/main/java/com/gitlab/tplsofteng/gamecorral/backing/GameSiteManagedBean.java
package com.gitlab.tplsofteng.gamecorral.backing;

//~--- non-JDK imports --------------------------------------------------------

import java.io.Serializable;
import java.util.Map;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletResponse;
import com.gitlab.tplsofteng.gamecorral.Entities.GameSiteUser;
import com.gitlab.tplsofteng.gamecorral.appwide.SessionManager;

/*
* To change this template, choose Tools | Templates and open the template in
* the editor.
 */

/**
 *
 * @author tplsofteng@gmail.com
 */
public class GameSiteManagedBean implements Serializable {
    protected SessionManager SessionMgr = SessionManager.getInstance();
    protected boolean        reloadNeeded;

    public GameSiteManagedBean() {
        SessionMgr = SessionManager.getInstance();
    }
    
    public String getActiveUserName() {
        String name = getActiveUser().getUserName();
        return name;
    }

    public GameSiteUser getActiveUser() {
        GameSiteUser user = SessionMgr.getUserForSessionId(readSessionId());
        return user;
    }

    public boolean isLoggedIn() 
    {
        boolean ans     = false;
        Cookie  session = readCookie("JSESSIONID");

        if (session != null) 
        {
            GameSiteUser user = SessionMgr.getUserForSessionId(session.getValue());

            if (user != null) 
            {
                ans = true;
            }
        }

        return ans;
    }

    // Convenience Method to read the current session cookie managed by the server
    public String readSessionId() {
        Cookie session = readCookie("JSESSIONID");

        return session.getValue();
    }

    public static Cookie readCookie(String name) {
        FacesContext        context = FacesContext.getCurrentInstance();
        Map<String, Object> cookies = context.getExternalContext().getRequestCookieMap();
        Cookie              cookie  = null;

        if (cookies.containsKey(name)) {
            cookie = (Cookie) cookies.get(name);
        }

        return cookie;
    }

    public static void writeCookie(Cookie cookie) {

        // Add a cookie to the browser
        FacesContext context = FacesContext.getCurrentInstance();

        ((HttpServletResponse) context.getExternalContext().getResponse()).addCookie(cookie);
    }
    
    public static void facesInfo(String message)
    {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(message));
    }
    
    public static void facesInfo(String summary, String detail)
    {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(summary, detail));
    }
    
    public static void facesWarn(String message)
    {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN ,"Message", message));
    }
    
    public static void facesWarn(String summary, String detail)
    {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN ,summary, detail));
    }
    
    public static void facesError(String message)
    {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR ,"Message", message));
    }
    
    public static void facesError(String summary, String detail)
    {
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR ,summary, detail));
    }

    /**
     * @return the reloadNeeded
     */
    public boolean isReloadNeeded() {
        return reloadNeeded;
    }

    /**
     * @param reloadNeeded the reloadNeeded to set
     */
    public void setReloadNeeded(boolean reloadNeeded) {
        this.reloadNeeded = reloadNeeded;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com

src/main/java/com/gitlab/tplsofteng/gamecorral/backing/SignupBean.java
package com.gitlab.tplsofteng.gamecorral.backing;

//~--- non-JDK imports --------------------------------------------------------

/*
* To change this template, choose Tools | Templates and open the template in
* the editor.
 */
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.transaction.SystemException;
import com.gitlab.tplsofteng.gamecorral.Entities.GameSiteUser;
import com.gitlab.tplsofteng.gamecorral.persistence.CrudServiceBean;

/**
 *
 * @author tplsofteng@gmail.com
 */
@ManagedBean(name = "SignupBean")
@RequestScoped
public class SignupBean {
    private CrudServiceBean dao;
    private String          password;

    /**
     * Creates a new instance of SignupBean
     */
    private String username;

    public SignupBean() {
        dao = new CrudServiceBean();
    }

    public void signup() {
        System.err.println("SIGNUP");

        FacesMessage msg     = null;
        GameSiteUser newUser = new GameSiteUser();

        newUser.setUserName(username);
        newUser.setPassword(password);

        if (dao.findUserIdByName(username) == -1) {
            try {
                dao.create(newUser);

                if (dao.findUserIdByName(newUser.getUserName()) != -1) {
                    msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Signup Success", username + " Account Created");
                } else {
                    msg = new FacesMessage(FacesMessage.SEVERITY_WARN, "Signup Error",
                                           "Something went wrong, Your account may not have been created");
                }
            } catch (SystemException ex) {
                msg = new FacesMessage(FacesMessage.SEVERITY_WARN, "Signup Error",
                                       "An error has occurred, your account has not been created");
            }
        } else {
            msg = new FacesMessage(FacesMessage.SEVERITY_WARN, "Signup Error", "Sorry That name is not available");
        }

        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }
}


//~ Formatted by Jindent --- http://www.jindent.com

src/main/java/com/gitlab/tplsofteng/gamecorral/backing/UsersPageBean.java
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package com.gitlab.tplsofteng.gamecorral.backing;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import com.gitlab.tplsofteng.gamecorral.Entities.GameSiteUser;
import com.gitlab.tplsofteng.gamecorral.persistence.CrudServiceBean;

/**
 *
 * @author tplsofteng@gmail.com
 */
@ManagedBean
@RequestScoped
@URLMapping(
    id      = "usersPage",
    pattern = "/users/#{usersPageBean.queryName}",
    viewId  = "/usersPage.xhtml"
)

public class UsersPageBean extends GameSiteManagedBean
{
    private String queryName;
    private GameSiteUser user;
    private CrudServiceBean dao;

    
    public UsersPageBean()
    {
       
        super();
        dao = new CrudServiceBean();
    }
    

    /**
     * @return the userName
     */
    public String getQueryName() {
        return queryName;
    }

    /**
     * @param userName the userName to set
     */
    public void setQueryName(String userName) {
        this.queryName = userName;
        
        if(user == null)
        {
            long id = dao.findUserIdByName(queryName);
            user = (GameSiteUser)dao.find(GameSiteUser.class, id);
        }
        
    }

    /**
     * @return the friends
     */
    public List<GameSiteUser> getFriends() {
        return user.getFriends();
    }

    /**
     * @param friends the friends to set
     */
    public void setFriends(ArrayList<GameSiteUser> friends) {
        this.user.setFriends(friends);
    }

    /**
     * @return the userName
     */
    public String getUserName() 
    {
        if(user !=null)
        {
            return user.getUserName();
        }
        else
        {
            return "User Not Found";
        }
        
    }

    /**
     * @param userName the userName to set
     */
    public void setUserName(String userName) 
    {
        if(user!= null)
        {
            this.user.setUserName(userName);
        }
    }
    
    public boolean userExists()
    {
        if(user == null)
        {
            return false;
        }
        else
        {
            return true;
        }
    }
    
    public boolean isFriend()
    {
        GameSiteUser temp = getActiveUser();
        if (user.getFriends().contains(temp))
        {
            
            return true;
        }
        
        else
        {
            return false;
        }
    }
    
    public boolean isActiveUser()
    {
        GameSiteUser temp = getActiveUser();
        if (temp.getUserId() == user.getUserId())
        {
            
            return true;
        }
        
        else
        {
            return false;
        }
    }
    
    public void sendFriendRequest()
    {
        GameSiteUser activeUser = getActiveUser();
        if(activeUser != null)
        {
            if(activeUser.getUserId() != user.getUserId())
            {
                user.addFriendRequest(activeUser.getUserId());
                user = (GameSiteUser)dao.update(user);
                if(user.getFriends().size() > 0)
                {
                    System.err.println(user.getFriends().get(0));
                }
                
                else
                {
                    facesInfo("Something Went wrong the request did not reach the user");
                }
            }
            
            else
            {
                facesInfo("Can't friend yourself ^^");
            }
        }
        else
        {
            facesInfo("Couldn't find user, request not sent");
            
        }
    }
    
}

web/about.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="./coreTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml">>

    <ui:define name="top">
        top
    </ui:define>

    <ui:define name="content">
        <h>
            
            How to:
            <ol>
            <li>Create an account at the sign up link on the menu</li>
            <li>Click the login box and enter your login details</li>
            <li>Once logged in click on "My Profile" and you will be taken to your page</li>
            <li>Click upload new game to upload a game to the site</li>
            <li>Follow the wizard and upload a zipped file containing your html5 game files</li>
            <li>Next input a unique name for your game and click next</li>
            <li>Finally submit your game and if it succeeds return to your profile</li>
            <li>Click the link to your created game to play</li>
            </ol>
            
        </h>
    </ui:define>

</ui:composition>

web/coreTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <h:outputStylesheet name="css/default.css"/>
        <h:outputStylesheet name="css/cssLayout.css"/>
        <link rel="shortcut icon" type="image/x-icon" href="#{request.contextPath}/images/favicon.ico"/>
        <title>::Game Corral::</title>
    </h:head>

    <h:body>
        <div id="top" class="top">
            <h2>::Game Corral::</h2>
            <h:form>
                <p:menubar>
                    <p:menuitem value="Home" url="#{requestScope.contextPath}/home.xhtml"/>
                    <p:menuitem value="Sign Up" url="#{requestScope.contextPath}/signup.xhtml"/>
                    <p:menuitem value="My Profile" url="#{requestScope.contextPath}/profile.xhtml"/>
                    <p:menuitem value="Games" url="#{requestScope.contextPath}/games.xhtml"/>
                    <p:menuitem value="About" url="#{requestScope.contextPath}/about.xhtml"/>
                    <p:graphicImage value="#{requestScope.contextPath}/images/login.png" />
                    <p:menuitem rendered="#{!usersPageBean.isLoggedIn()}" value="login" onclick="dlg.show()" />
                    <p:menuitem rendered="#{usersPageBean.isLoggedIn()}" value="#{usersPageBean.activeUserName}" onclick="dlg.show()"/>
                </p:menubar>
                <p:dialog id="dialog" header="Login" widgetVar="dlg">  
                      
                        <h:panelGrid columns="2" cellpadding="5">  
                            <h:outputLabel for="username" value="Username: *" />  
                            <p:inputText value="#{LoginBean.username}"   
                                    id="username" required="true" label="username" />  

                            <h:outputLabel for="password" value="Password: * " />  
                            <h:inputSecret value="#{LoginBean.password}"   
                                    id="password" required="true" label="password" />  

                            <f:facet name="footer">  
                            <p:commandButton value="Login"  
                                actionListener="#{LoginBean.login}"   
                                oncomplete="handleLoginRequest(xhr, status, args)"/>  
                            </f:facet>   
                        </h:panelGrid>  
                      
                </p:dialog>
                </h:form>
  
                <script type="text/javascript">  
                    function handleLoginRequest(xhr, status, args) {  
                    if(args.validationFailed || !args.loggedIn) {
                        console.log("HERE");
                        jQuery('#dialog').parent().effect("shake", { times:3 }, 100);  
                    } else {  
                    dlg.hide();  
                    jQuery('#loginLink').fadeOut();  
                    }  
    }  
</script>  
            <ui:insert name="top">Top</ui:insert>
        </div>
            <div id="left">
                
            </div>
            <div id="content" class="left_content">

                <ui:insert name="content">Content</ui:insert>
                <h:form>
                    <p:growl id="globalmessages" showDetail="true" life="3000" autoUpdate="true"/>
                </h:form>
            </div>
    </h:body>

</html>

web/errorPage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <body>

        <ui:composition template="./coreTemplate.xhtml">

            <ui:define name="top">
                top
            </ui:define>

            <ui:define name="content">
                content
            </ui:define>

        </ui:composition>

    </body>
</html>

web/gamePage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <body>

        <ui:composition template="./coreTemplate.xhtml">

            <ui:define name="top">
                top
            </ui:define>
            
            <ui:define name="left">
                <p:graphicImage value="#{gamePageBean.getThumb}"/>
            </ui:define>

            <ui:define name="content">
                <p:panel header="#{gamePageBean.getGame()}">
                        
                    <h:outputText id="gamePage" value="#{gamePageBean.getPageContent()}" escape="false"/>
                    
                    <canvas id='c' tabindex='-1' style="outline:0"></canvas>
                    <br/>POINTS: <span id="points">0</span>

                    <script>
                       #{gamePageBean.content}
                    </script>
                    
                    
                </p:panel>
                
            </ui:define>

        </ui:composition>

    </body>
</html>

web/games.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <body>

        <ui:composition template="./coreTemplate.xhtml">
            
            <ui:define name="top">
                top
            </ui:define>

            <ui:define name="content">
                <p:carousel value="#{GamesPageBean.topGames}" var="game" itemStyleClass="gameStyle">
                </p:carousel>
            </ui:define>

        </ui:composition>

    </body>
</html>

web/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <body>

        <ui:composition template="./coreTemplate.xhtml">

            <ui:define name="top">
                top
            </ui:define>

            <ui:define name="content">
                <h:form>
                <p:carousel value="#{HomePageBean.trendingGames}" var="game" itemStyleClass="gameItem">  
                    <h:panelGrid columns="1" style="width:100%" cellpadding="5">  
                        <p:graphicImage value="#{game.thumb}"/>   

                        <h:outputText value="Author: #{game.uploader}" />  

                        <h:outputText value="Title: #{game.title}" />  
                    </h:panelGrid>  
                </p:carousel>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

web/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" 
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <body>

        <ui:composition template="./coreTemplate.xhtml">
            
            
            <ui:define name="top">
                
            </ui:define>

            <ui:define name="left">
                
            </ui:define>

            <ui:define name="content">
                <c:choose>
                    <c:when test="#{profilePageBean.isLoggedIn()}">
                        #{profilePageBean.initialize()}
                        
                        <p:panel id="profile" header="#{profilePageBean.userName}'s Profile">
                            <h:outputText value="Points: #{profilePageBean.points}"/>
                        </p:panel>
                        
                        <p:panel id="friends" header="#{profilePageBean.userName}'s Friends">
                            <h:form>
                            <p:dataGrid var="friend" value="#{profilePageBean.friends}" columns="3">
                                <p:column>
                                <p:panel header="#{friend.userName}">
                                    <p:graphicImage value="#{friend.avatar}"/>
                                </p:panel>
                                </p:column>
                            </p:dataGrid>
                            </h:form>
                        </p:panel>
                        
                        <p:panel id="games" header="#{profilePageBean.userName}'s Games">
                            <h:form>
                                <h:link outcome="uploadGame.xhtml" value="Upload a new game" >
                                        <h:graphicImage library="images" name="default.png" />
                                </h:link>
                                <p:dataGrid var="game" value="#{profilePageBean.games}" columns="3"> 
                                <p:column>
                                    #{profilePageBean.refresh()}
                                    <p:panel header="#{game.title}">
                                        <h:outputLink id="gameLink" value="#{request.contextPath}/games/#{game.title}">
                                            #{game.title}
                                        </h:outputLink>
                                    <p:graphicImage value="#{game.thumb}"/>
                                    </p:panel>
                                </p:column>
                            </p:dataGrid>
                            </h:form>  
                        </p:panel>   
                    </c:when>
                    <c:otherwise>
                    <P>Please Login</P>
                    </c:otherwise>
                </c:choose>
                
            </ui:define>

        </ui:composition>

    </body>
</html>

web/uploadGame.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="./coreTemplate.xhtml">

            <ui:define name="top">
                top
            </ui:define>

            <ui:define name="content">
                <h:form rendered="#{profilePageBean.loggedIn}">
                    <p:panel header="Upload a new Game">
                        <p:wizard widgetVar="wiz"  
                                    flowListener="#{uploadGameBean.onGameUploadFlowProcess}">  
                            
                            <p:tab id="gamefiles" title="Files">  
                                <p:panel header="Game Files">  

                                    <h:messages errorClass="error"/>  

                                    <h:panelGrid columns="2" columnClasses="label, value">
                                        <h:form id="gameUploadWizForm" enctype="multipart/form-data">
                                            <h:outputLabel value="Upload Zip File"/>
                                            <p:fileUpload fileUploadListener="#{uploadGameBean.handleGameUpload}"  
                                                mode="advanced"    
                                                sizeLimit="1000000"   
                                                allowTypes="/(\.|\/)(zip)$/"/>  
                                        </h:form>

                                        <h:form id="gameAvatarWizForm" enctype="multipart/form-data">
                                            <h:outputLabel value="Upload Thumbnail File"/>
                                            <p:fileUpload fileUploadListener="#{uploadGameBean.handleIconUpload}"  
                                                mode="advanced"   
                                                sizeLimit="100000"   
                                                allowTypes="/(\.|\/)(jpg|png|gif)$/"/>  
                                        </h:form> 
                                    </h:panelGrid>  
                                </p:panel>  
                            </p:tab>
                            
                            <p:tab id="gameattribs" title="Attributes">  

                                <p:panel header="Game Attributes">  

                                    <h:messages id="gameuploaderror" errorClass="gameuploaderror"/>

                                    <h:panelGrid columns="2" columnClasses="label, value" styleClass="grid">  
                                        <h:outputText value="Game Title: " />  
                                        <p:inputText required="true" label="Game Title"  
                                                     value="#{uploadGameBean.title}" />  
                                    </h:panelGrid>  
                                </p:panel>  
                            </p:tab>  

                            <p:tab id="confirm" title="Confirm">  
                                <p:panel header="Confirmation">  

                                    <h:panelGrid id="confirmation" columns="6">  
                                        <h:outputText value="Game Title: " />  
                                        <h:outputText styleClass="outputLabel"  
                                                        value="#{uploadGameBean.currentGame.title}"/>  
                                    </h:panelGrid>
                                    <p:commandButton value="Submit Game"   
                                                        actionListener="#{uploadGameBean.commitUpload}"/>

                                </p:panel>  
                            </p:tab>  

                        </p:wizard>  

                        <p:ajaxStatus>  
                            <f:facet name="start">  
                                <h:graphicImage value="../design/ajaxloading.gif" />  
                            </f:facet>  

                            <f:facet name="complete">  
                                <h:outputText value="" />  
                            </f:facet>  
                        </p:ajaxStatus>  
                    </p:panel>
                </h:form>
                <h:form rendered="#{!profilePageBean.loggedIn}">
                    <p:panel header="Please log in">
                          
                    </p:panel>
                </h:form> 
            </ui:define>

        </ui:composition>

    </body>
</html>